# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11.2
language: objective-c
cache: cocoapods
podfile: Example/Podfile

matrix:
  include:
    - osx_image: xcode11.2
      env: XCODETEST_SIMULATOR='platform=iOS Simulator,name=iPhone 8,OS=13.2'
    - osx_image: xcode11.2
      env: XCODETEST_SIMULATOR='platform=iOS Simulator,name=iPhone 8,OS=12.2'
    - osx_image: xcode11.2
      env: XCODETEST_SIMULATOR='platform=iOS Simulator,name=iPhone 8,OS=11.4'
    - osx_image: xcode10.1
      env: XCODETEST_SIMULATOR='platform=iOS Simulator,name=iPhone 6,OS=10.3.1'
    - osx_image: xcode10.1
      env: XCODETEST_SIMULATOR='platform=iOS Simulator,name=iPhone 6,OS=9.3'

before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild clean test -enableCodeCoverage YES -workspace Example/Zama.xcworkspace -scheme Zama-Unit-Tests -destination "$XCODETEST_SIMULATOR" ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
